"""add date of birth in person table

Revision ID: 25968da37b9f
Revises: 889df96edc1e
Create Date: 2024-11-10 15:13:03.049838

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25968da37b9f'
down_revision = '889df96edc1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('person', sa.Column('date_of_birth', sa.Date(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('person', 'date_of_birth')
    # ### end Alembic commands ###
