"""add log table

Revision ID: 889df96edc1e
Revises: 8acde317d657
Create Date: 2024-10-15 15:27:16.175656

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '889df96edc1e'
down_revision = '8acde317d657'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('method', sa.String(), nullable=False),
    sa.Column('path', sa.String(), nullable=False),
    sa.Column('parameters', sa.String(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('log')
    # ### end Alembic commands ###
